# Hyprland configuration overrides
# Add your custom settings here

# Shell scripts bindings
unbind = SUPER SHIFT, P
unbind = SUPER SHIFT, Z
unbind = SUPER SHIFT, U
unbind = SUPER SHIFT, I
unbind = SUPER SHIFT, W
unbind = SUPER SHIFT, semicolon
bindd = SUPER SHIFT, P, Project Launcher, exec, $HOME/.local/bin/kc-project-launch
bindd = SUPER SHIFT, Z, Session Launcher, exec, $HOME/.local/bin/kc-project-launch-active
bindd = SUPER SHIFT, U, Bookmark Launcher, exec, $HOME/.local/bin/kc-bookmark-launch
bindd = SUPER SHIFT, I, Cheatsheet Launcher, exec, $HOME/.local/bin/kc-cheatsheet-launch
bindd = SUPER SHIFT, W, Web Search, exec, $HOME/.local/bin/kc-search-launch
bindd = SUPER SHIFT, semicolon, Git Repo Status, exec, $HOME/.local/bin/kc-git-repo-status

# Screenshot Capture bindings
unbind = SUPER SHIFT, C
bindd = SUPER SHIFT, C, Screenshot with editing, exec, omarchy-cmd-screenshot

# Custom window rules for my workflow
windowrule = match:class code, workspace 2
windowrule = match:class brave-browser, workspace 3
windowrule = match:class obsidian, workspace 10
windowrule = match:class chromium, workspace 4
windowrule = match:class DBeaver, workspace 5
windowrule = workspace 9, match:class ^(org.keepassxc.KeePassXC|keepassxc)$
windowrule = workspace 9, match:initial_class ^(org.keepassxc.KeePassXC|keepassxc)$
