# Hyprland configuration overrides
# Add your custom settings here

# Example overrides:
# $mainMod = SUPER

# Use single default monitor (see all monitors with: hyprctl monitors)
# monitor=,preferred,auto,1.6

bindd = SUPER SHIFT, P, Project Launcher, exec, /home/kob/Repos/shell-scripts/project-launch.sh
bindd = SUPER SHIFT, U, Project Launcher, exec, /home/kob/Repos/shell-scripts/bm-launch.sh

unbind = SUPER, B
bindd = SUPER, B, Browser, exec, $browser

